/* =========================================================
   Content: translations + projects
   To add a project: copy one object in PROJECTS and edit it.
   ========================================================= */

const IMG = 'assets/img/';

const I18N = {
  ar: {
    langSwitch: 'EN',
    brandName: 'م. إبراهيم سمير',
    brandRole: 'مطوّر تطبيقات ومواقع',
    navWork: 'أعمالي', navSimulator: 'المحاكي', navServices: 'الخدمات', navAdvisor: 'مستشار التقنيات', navProcess: 'طريقة العمل', navAbout: 'عنّي', faqTitleShort: 'الأسئلة الشائعة', navContact: 'تواصل معي', navHire: 'ابدأ مشروعك',
    heroAvail: 'متاح لمشاريع جديدة الآن', heroAvailShort: 'متاح للعمل',
    heroTitle1: 'أحوّل فكرتك إلى', heroTitle2: 'تطبيق وموقع يبيع',
    heroIBuild: 'أبني',
    typed: ['تطبيقات موبايل Android و iOS', 'متاجر إلكترونية بتبيع', 'لوحات تحكم وأنظمة إدارة', 'منصات تعليمية متكاملة', 'تطبيقات منشورة على المتاجر'],
    heroSub: 'مهندس برمجيات متخصص في Flutter و Next.js. أصمّم وأبرمج وأنشر تطبيقات موبايل ومواقع ولوحات تحكم بجودة عالمية — من أول فكرة لحد ما التطبيق يبقى على App Store و Google Play.',
    ctaWork: 'شوف أعمالي', ctaWhats: 'كلّمني واتساب',
    trustClients: 'عملاء في 10 دول',
    fcRafiq: 'رفيق المسلم', fcSmooth: 'أداء سلس', fcPublished: 'تم النشر',
    statYears: 'سنوات خبرة', statApps: 'تطبيق منشور على المتاجر', statProjects: 'مشروع على GitHub', statCountries: 'دول: مصر · السعودية · الكويت · الإمارات · قطر · عُمان · البحرين · ألمانيا · العراق · الأردن', flipHint: 'مرّر الماوس لتقليب الصور',
    featEyebrow: 'أبرز الأعمال', featTitle: 'مشاريع حقيقية شغّالة مع عملاء حقيقيين',
    featSub: 'كل مشروع هنا اتسلّم لعميل أو اتنشر على المتاجر. اضغط على أي مشروع تشوف صوره وتفاصيله.',
    allEyebrow: 'معرض الأعمال', allTitle: 'كل المشاريع', allSub: 'تطبيقات موبايل، مواقع، متاجر ولوحات تحكم — اختار القسم اللي يهمك.',
    fAll: 'الكل', fMobile: 'تطبيقات موبايل', fWeb: 'مواقع ومتاجر', fLive: 'منشور ولايف',
    moreGithub: 'شوف كل الكود على GitHub',
    srvEyebrow: 'الخدمات', srvTitle: 'كل اللي مشروعك محتاجه في مكان واحد', srvSub: 'من التصميم للبرمجة للنشر والدعم بعد الإطلاق.',
    procEyebrow: 'طريقة العمل', procTitle: '4 خطوات من الفكرة للإطلاق', procSub: 'شفافية كاملة، وتحديثات مستمرة، وإنت متابع كل حاجة أول بأول.',
    aboutEyebrow: 'عنّي', aboutTitle: 'مش مجرد كود — منتج يكبّر شغلك',
    aboutRole: 'مهندس برمجيات · Flutter و Web',
    aboutP1: 'أنا إبراهيم، مهندس برمجيات بخبرة أكتر من 4 سنين في بناء تطبيقات موبايل ومواقع جاهزة للإنتاج. نشرت أكتر من 10 تطبيقات على App Store و Google Play لعملاء في 10 دول، منها مصر ودول الخليج وألمانيا والعراق والأردن.',
    aboutP2: 'بشتغل بـ Clean Architecture و SOLID عشان الكود يفضل نضيف وسهل يتطور، وبجهّز CI/CD يخلّي كل تحديث يوصل لعملائك بسرعة ومن غير مشاكل.',
    aboutEdu: 'بكالوريوس علوم الحاسب — جامعة المنوفية', aboutLoc: 'مصر — أعمل مع عملاء من كل مكان', aboutLang: 'عربي · English',
    ctEyebrow: 'يلا نبدأ', ctTitle: 'عندك فكرة؟ خلّينا نحوّلها لمنتج حقيقي',
    ctSub: 'ابعتلي تفاصيل مشروعك وهرد عليك خلال ساعات بخطة واضحة وعرض سعر مناسب.',
    ctWhats: 'واتساب', ctEmail: 'البريد الإلكتروني',
    fName: 'اسمك', fNamePh: 'مثال: أحمد محمد', fType: 'نوع المشروع', fBudget: 'الميزانية التقريبية',
    fMsg: 'احكيلي عن فكرتك', fMsgPh: 'عايز تطبيق لمطعمي فيه منيو وطلبات أونلاين...',
    fSend: 'ابعت على واتساب', fNote: 'الرسالة هتتفتح جاهزة في واتساب — مجرد ضغطة إرسال.',
    types: ['تطبيق موبايل (Android و iOS)', 'موقع / متجر إلكتروني', 'لوحة تحكم / نظام إدارة', 'تطبيق + موقع مع بعض', 'تطوير أو إصلاح مشروع قائم'],
    budgets: ['لسه مش محدد', 'أقل من 500$', '500$ – 1,500$', '1,500$ – 4,000$', 'أكتر من 4,000$'],
    waIntro: 'أهلاً م. إبراهيم 👋', waName: 'الاسم', waType: 'نوع المشروع', waBudget: 'الميزانية', waMsg: 'التفاصيل',
    footerRights: 'كل الحقوق محفوظة.',
    tapToMail: '— اضغط وابعتلي على طول',
    ftCtaTitle: 'جاهز تحوّل فكرتك لتطبيق بيكسب؟', ftCtaSub: 'استشارة مجانية + خطة واضحة وعرض سعر خلال 24 ساعة.', ftEmailMe: 'ابعتلي إيميل', ftAbout: 'بحوّل الأفكار لتطبيقات موبايل ومواقع ولوحات تحكم بجودة عالمية — +10 تطبيقات منشورة وعملاء في 10 دول.', ftLinks: 'روابط سريعة', ftServices: 'الخدمات', ftContact: 'تواصل معايا', ftLocation: 'مصر — أونلاين لكل الدول', ftHours: 'متاح 7 أيام في الأسبوع', ftSig: 'تصميم وتطوير', sigName: 'المهندس إبراهيم سمير',
    live: 'لايف', onStores: 'منشور على المتاجر', viewDetails: 'التفاصيل والصور', features: 'المميزات', tech: 'التقنيات',
    appStore: 'App Store', googlePlay: 'Google Play', liveSite: 'زيارة الموقع', code: 'الكود', screenshots: 'صورة',
    mobile: 'موبايل', web: 'ويب', system: 'أنظمة', practice: 'تدريب',
    fSystem: 'أنظمة وذكاء اصطناعي', fPractice: 'تدريبات وواجهات', showMore: 'عرض المزيد', showLess: 'عرض أقل', concept: 'تصميم توضيحي للمشروع — الصور الحقيقية من داخل التطبيق قريبًا', projectsCount: 'مشروع',
    brandsTitle: 'براندات ومنتجات اشتغلت عليها', brManara: 'منارة', brAladeeb: 'الأديب', brMetro: 'مترو مصر',
    ghEyebrow: 'شغّال كل يوم', ghTitle: 'نشاطي على GitHub', ghSub: 'الأرقام دي بتتحدث لوحدها من GitHub — كود حقيقي، مشاريع حقيقية.', ghRepos: 'مشروع عام', ghFollowers: 'متابع', ghYears: 'سنين على GitHub', ghFollow: 'تابعني على GitHub',
    wallEyebrow: 'من المعرض', wallTitle: 'مشروع بين موبايل وويب وأنظمة ذكية',
    simEyebrow: 'المحاكي التفاعلي', simTitle: 'جرّب التطبيقات بنفسك على جهاز حي',
    simSub: 'تفاعل مع الشاشات، اختبر سلاسة الـ 60 FPS، وجرّب واجهات Clean Architecture مبنية بـ Flutter بأعلى معايير آبل وجوجل.',
    simAppQuickin: 'QuickIn — شاليهات وإقامات', simAppRafiq: 'رفيق المسلم (تقييم 5.0)', simAppDw: 'Deutsche Welt للألماني',
    simFpsBadge: '60.0 FPS · محرك Impeller', simTapHint: 'المس الشاشة أو بدّل بين التبويبات', simCta: 'عايز تطبيق بنفس السلاسة والجودة؟', simCtaBtn: 'احسب تكلفة فكرتك',
    advEyebrow: 'جديد · مستشار المعمارية الذكي', advTitle: 'اكتشف أفضل معمارية تقنية لمشروعك',
    advSub: 'اختر طبيعة مشروعك وأولوياتك، وسيقوم الذكاء الاصطناعي بتحديد الـ Stack والمعمارية الأنسب لضمان أقصى سرعة وأقل تكلفة صيانة.',
    advStep1: '1. نوع المشروع', advStep2: '2. أولويتك الكبرى', advStep3: '3. مميزات خاصة',
    advGenBtn: 'توليد المعمارية والمواصفات', advCardTitle: 'المخطط المعماري المقترح لمشروعك',
    advFrontend: 'واجهة المستخدم (Frontend)', advState: 'المعمارية وإدارة الحالة', advBackend: 'الباك إند وقواعد البيانات', advDevOps: 'النشر والأتمتة (DevOps)',
    advWhy: 'لماذا هذه المعمارية تحديداً؟', advSimilar: 'مشروع حقيقي مشابه في البورتفوليو:', advBookWhatsapp: 'احجز استشارة على هذا المعمار',
    faqEyebrow: 'وضوح تام قبل البدء', faqTitle: 'الأسئلة الشائعة وحقوقك كاملة',
    faqSub: 'كل ما تحتاج معرفته عن ملكية السورس كود، حسابات المتاجر، نظام الدفعات، والضمان بعد التسليم.',
    faqAskPh: 'عندك سؤال مختلف؟ اكتبه هنا وسيجيبك المساعد الذكي فورًا...', faqAskBtn: 'اسأل الذكاء الاصطناعي',
  },
  en: {
    langSwitch: 'ع',
    brandName: 'Eng. Ebrahim Samir',
    brandRole: 'Mobile & Web Developer',
    navWork: 'Work', navSimulator: 'Playground', navServices: 'Services', navAdvisor: 'Tech Advisor', navProcess: 'Process', navAbout: 'About', faqTitleShort: 'FAQ', navContact: 'Contact', navHire: 'Start a project',
    heroAvail: 'Available for new projects', heroAvailShort: 'Available',
    heroTitle1: 'I turn your idea into', heroTitle2: 'apps & websites that sell',
    heroIBuild: 'I build',
    typed: ['Android & iOS mobile apps', 'e-commerce stores that convert', 'admin dashboards & systems', 'full e-learning platforms', 'apps live on the stores'],
    heroSub: 'Software engineer specialised in Flutter and Next.js. I design, build and ship world-class mobile apps, websites and dashboards — from the first idea until your app is live on the App Store and Google Play.',
    ctaWork: 'See my work', ctaWhats: 'Chat on WhatsApp',
    trustClients: 'Clients in 10 countries',
    fcRafiq: 'Rafiq Muslim', fcSmooth: 'Smooth performance', fcPublished: 'Published',
    statYears: 'Years of experience', statApps: 'Apps live on the stores', statProjects: 'Projects on GitHub', statCountries: 'Countries: Egypt · KSA · Kuwait · UAE · Qatar · Oman · Bahrain · Germany · Iraq · Jordan', flipHint: 'Hover to flip the screens',
    featEyebrow: 'Featured work', featTitle: 'Real products, shipped for real clients',
    featSub: 'Every project here was delivered to a client or published on the stores. Tap any project to see screenshots and details.',
    allEyebrow: 'Portfolio', allTitle: 'All projects', allSub: 'Mobile apps, websites, stores and dashboards — pick what interests you.',
    fAll: 'All', fMobile: 'Mobile apps', fWeb: 'Websites & stores', fLive: 'Live & published',
    moreGithub: 'See all the code on GitHub',
    srvEyebrow: 'Services', srvTitle: 'Everything your product needs, in one place', srvSub: 'From design to development to launch and post-launch support.',
    procEyebrow: 'Process', procTitle: '4 steps from idea to launch', procSub: 'Full transparency, frequent updates, and you stay in the loop at every stage.',
    aboutEyebrow: 'About', aboutTitle: 'Not just code — a product that grows your business',
    aboutRole: 'Software Engineer · Flutter & Web',
    aboutP1: "I'm Ebrahim, a software engineer with 4+ years of experience building production-ready mobile apps and websites. I've shipped 10+ apps to the App Store and Google Play for clients in 10 countries, including Egypt, the Gulf states, Germany, Iraq and Jordan.",
    aboutP2: 'I work with Clean Architecture and SOLID so your codebase stays clean and easy to grow, and I set up CI/CD so every update reaches your users quickly and safely.',
    aboutEdu: 'B.Sc. Computer Science — Menoufia University', aboutLoc: 'Egypt — working with clients worldwide', aboutLang: 'Arabic · English',
    ctEyebrow: "Let's talk", ctTitle: "Have an idea? Let's turn it into a real product",
    ctSub: "Send me your project details and I'll get back to you within hours with a clear plan and a fair quote.",
    ctWhats: 'WhatsApp', ctEmail: 'Email',
    fName: 'Your name', fNamePh: 'e.g. John Smith', fType: 'Project type', fBudget: 'Estimated budget',
    fMsg: 'Tell me about your idea', fMsgPh: 'I need an app for my restaurant with a menu and online ordering...',
    fSend: 'Send via WhatsApp', fNote: 'Your message opens ready in WhatsApp — just hit send.',
    types: ['Mobile app (Android & iOS)', 'Website / online store', 'Dashboard / management system', 'App + website together', 'Improve or fix an existing project'],
    budgets: ['Not sure yet', 'Under $500', '$500 – $1,500', '$1,500 – $4,000', 'Over $4,000'],
    waIntro: 'Hi Eng. Ebrahim 👋', waName: 'Name', waType: 'Project type', waBudget: 'Budget', waMsg: 'Details',
    footerRights: 'All rights reserved.',
    tapToMail: '— tap to email me instantly',
    ftCtaTitle: 'Ready to turn your idea into an app that earns?', ftCtaSub: 'Free consultation + a clear plan and quote within 24 hours.', ftEmailMe: 'Email me', ftAbout: 'I turn ideas into world-class mobile apps, websites and dashboards — 10+ published apps and clients in 10 countries.', ftLinks: 'Quick links', ftServices: 'Services', ftContact: 'Get in touch', ftLocation: 'Egypt — working online worldwide', ftHours: 'Available 7 days a week', ftSig: 'Designed & developed by', sigName: 'Engineer Ebrahim Samir',
    live: 'Live', onStores: 'On the stores', viewDetails: 'Details & screenshots', features: 'Highlights', tech: 'Tech stack',
    appStore: 'App Store', googlePlay: 'Google Play', liveSite: 'Visit website', code: 'Code', screenshots: 'screenshots',
    mobile: 'Mobile', web: 'Web', system: 'Systems', practice: 'Practice',
    fSystem: 'Systems & AI', fPractice: 'Practice & UI', showMore: 'Show more', showLess: 'Show less', concept: 'Concept cover designed for this project', projectsCount: 'projects',
    brandsTitle: 'Brands & products I have built for', brManara: 'Manara', brAladeeb: 'Al-Adeeb', brMetro: 'Metro Masr',
    ghEyebrow: 'Shipping every day', ghTitle: 'My GitHub activity', ghSub: 'These numbers update live from GitHub — real code, real projects.', ghRepos: 'Public repos', ghFollowers: 'Followers', ghYears: 'Years on GitHub', ghFollow: 'Follow me on GitHub',
    wallEyebrow: 'From the portfolio', wallTitle: 'projects across mobile, web & smart systems',
    simEyebrow: 'Interactive Playground', simTitle: 'Experience Live Apps on a Realistic Device',
    simSub: 'Interact with real screens, test 60 FPS fluidity, and experience Clean Architecture Flutter apps built to Apple & Google standards.',
    simAppQuickin: 'QuickIn — Stays & Chalets', simAppRafiq: 'Rafiq Muslim (5.0 Rating)', simAppDw: 'Deutsche Welt Academy',
    simFpsBadge: '60.0 FPS · Impeller Engine', simTapHint: 'Tap screens or switch tabs below', simCta: 'Want an app with this polish & speed?', simCtaBtn: 'Estimate Your Idea',
    advEyebrow: 'NEW · AI Tech Advisor', advTitle: 'Discover the Optimal Architecture for Your Project',
    advSub: 'Select your project scope and operational priorities. AI will generate an engineering blueprint balancing maximum performance with cost efficiency.',
    advStep1: '1. Project Scope', advStep2: '2. Core Priority', advStep3: '3. Key Features',
    advGenBtn: 'Generate Tech Blueprint', advCardTitle: 'Recommended Architecture Blueprint',
    advFrontend: 'Frontend UI Layer', advState: 'Architecture & State Management', advBackend: 'Backend & Database', advDevOps: 'Deployment & CI/CD',
    advWhy: 'Why This Architecture?', advSimilar: 'Live Portfolio Proof:', advBookWhatsapp: 'Book Consultation on this Blueprint',
    faqEyebrow: 'Full Transparency', faqTitle: 'Frequently Asked Questions & Your Rights',
    faqSub: 'Everything you need to know about source code ownership, store accounts, milestone payments, and post-launch warranty.',
    faqAskPh: 'Have another question? Ask here for an instant AI answer...', faqAskBtn: 'Ask AI',
  },
};

const SERVICES = [
  { icon: 'phone', ar: ['تطبيقات موبايل', 'تطبيق واحد يشتغل على Android و iOS بأداء أصلي 60 FPS، بتصميم مطابق للـ Figma.'], en: ['Mobile apps', 'One codebase for Android & iOS with native-feeling 60 FPS performance, pixel-perfect from Figma.'] },
  { icon: 'web', ar: ['مواقع ومتاجر إلكترونية', 'مواقع سريعة ومتوافقة مع SEO وتدعم العربي RTL، ومتاجر فيها سلة ودفع وشحن.'], en: ['Websites & online stores', 'Fast, SEO-friendly sites with full Arabic RTL support, and stores with cart, payments and shipping.'] },
  { icon: 'dash', ar: ['لوحات تحكم وأنظمة إدارة', 'لوحة تدير منها المنتجات والطلبات والعملاء والأرباح بسهولة ومن أي مكان.'], en: ['Dashboards & admin systems', 'Manage products, orders, customers and profit easily — from anywhere.'] },
  { icon: 'rocket', ar: ['النشر على المتاجر', 'أتولى رفع التطبيق على App Store و Google Play، وأجهّز CI/CD للتحديثات التلقائية.'], en: ['Store publishing', 'I handle App Store & Google Play release, plus CI/CD pipelines for automatic updates.'] },
  { icon: 'db', ar: ['باك إند وتكاملات', 'Firebase و Supabase و REST APIs، مع بوابات الدفع والخرائط والإشعارات.'], en: ['Backend & integrations', 'Firebase, Supabase and REST APIs, with payment gateways, maps and push notifications.'] },
  { icon: 'shield', ar: ['صيانة ودعم وأمان', 'تحسين أداء، إصلاح مشاكل، تخزين آمن وتشفير، ودعم مستمر بعد الإطلاق.'], en: ['Maintenance, support & security', 'Performance tuning, bug fixes, secure storage & encryption, and ongoing post-launch support.'] },
];

const PROCESS = [
  { ar: ['نتكلم ونخطط', 'نفهم فكرتك وجمهورك، ونحدد المميزات والمدة والتكلفة بشكل واضح.'], en: ['Discover & plan', 'We understand your idea and audience, then lock scope, timeline and cost clearly.'] },
  { ar: ['التصميم', 'تصميم واجهات عصرية وسهلة، وتوافق عليها قبل ما نبدأ برمجة.'], en: ['Design', 'Modern, intuitive screens that you approve before any code is written.'] },
  { ar: ['البرمجة والمتابعة', 'تطوير بكود نضيف، مع نسخ تجريبية بتجربها بنفسك وتحديثات مستمرة.'], en: ['Build & review', 'Clean code with test builds you can try yourself, plus regular progress updates.'] },
  { ar: ['الإطلاق والدعم', 'نشر على المتاجر أو السيرفر، وتسليم كامل، ودعم بعد الإطلاق.'], en: ['Launch & support', 'Release to the stores or server, full handover, and support after launch.'] },
];

const WHY = [
  { icon: 'layers', ar: 'Clean Architecture و SOLID', en: 'Clean Architecture & SOLID' },
  { icon: 'rocket', ar: 'CI/CD ونشر تلقائي', en: 'CI/CD & automated releases' },
  { icon: 'shield', ar: 'تخزين آمن وتشفير', en: 'Secure storage & encryption' },
  { icon: 'offline', ar: 'يشتغل بدون إنترنت', en: 'Offline-first resilience' },
  { icon: 'zap', ar: 'واجهات 60 FPS', en: 'Pixel-perfect 60 FPS UI' },
  { icon: 'globe', ar: 'عربي RTL وإنجليزي', en: 'Arabic RTL & English' },
];

const STACK = ['Flutter', 'Dart', 'BLoC / Cubit', 'Clean Architecture', 'Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Firebase', 'Supabase', 'REST / Dio', 'GraphQL', 'WebSockets', 'Django REST', 'GitHub Actions', 'Fastlane', 'Google Maps', 'Framer Motion'];
